### ISSUE TITLE
Newer Version 1.3 is throwing Read Timeout Error even though  throwExceptionOnTimeout="false" 

### ISSUE THREAD

**Issue by devanad** [mulesoft/mule-module-requester#21]
Hi, 

I have existing projects which is working fine without any issues. and i migrated that project to newer version of Mule and Newer version of mule-module-requester and it's stopped working due to unnecessary errors which is thrown from Mule-requester API 

I was using mule-module-requester 1.2 version previously and now moved to 1.3 version of mule requester as newer version of Mule 3.7.3 has newer version of the Spring API and it will not work with older version of mule requester so i moved it to 1.3 version of requester

Sample Code:

	<flow name="Mule_Common_FTP_EDI_FilesProcessing_Inbound" 
		processingStrategy="synchronous">
        <quartz:inbound-endpoint repeatInterval="${ftp.edi.inbound.repeatInterval}" responseTimeout="${ftp.edi.inbound.root.responseTimeout}" jobName="pollingFTPFiles" doc:name="Quartz"  connector-ref="pollingFTPFilesConnector">
            <quartz:event-generator-job stateful="true"/>
       </quartz:inbound-endpoint>
       <set-payload value="#[[${ftp.edi.inbound.carriers.path}]]" doc:name="Set Payload"/>
        <foreach doc:name="For Each">
          <mulerequester:request config-ref="FTP_Requester" resource="#[flowVars.reqesterReference]" throwExceptionOnTimeout="false" doc:name="Mule Requester"/>
	</foreach>
	  <exception-strategy ref="Catch_Exception_Strategy" doc:name="Reference Exception Strategy"/>	
	</flow>

Following one is my exception stack trace. : 

ERROR 2015-12-17 16:57:28,891 [scheduler-edi-ftp-files-processing_Worker-4] org.mule.exception.CatchMessagingExceptionStrategy: 
********************************************************************************
Message               : Failed to receive event over: DefaultInboundEndpoint{endpointUri=ftp://XXX:<password>@XXXX.com/EDI/UAT/XXXXX/InBound/, connector=EEFtpConnector
{
  name=connector.ftp.mule.default
  lifecycle=start
  this=4fd998e8
  numberOfConcurrentTransactedReceivers=4
  createMultipleTransactedReceivers=true
  connected=true
  supportedProtocols=[ftp]
  serviceOverrides=<none>
}
,  name='endpoint.ftp.XXXXX.com.21.EDI.UAT.XXXX.UAT.InBound', mep=ONE_WAY, properties={}, transactionConfig=Transaction{factory=null, action=INDIFFERENT, timeout=0}, deleteUnacceptedMessages=false, initialState=started, responseTimeout=10000, endpointEncoding=UTF-8, disableTransportTransformer=false} (timeout=1000)
Type                  : org.mule.api.transport.ReceiveException
Code                  : MULE_ERROR-92
Timeout               : 1000
JavaDoc               : http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/transport/ReceiveException.html
Endpoint              : DefaultInboundEndpoint{endpointUri=ftp://svelmurugan:<password>@XXXX.com/EDI/UAT/XXXXX/InBound/, connector=EEFtpConnector
{
  name=connector.ftp.mule.default
  lifecycle=start
  this=4fd998e8
  numberOfConcurrentTransactedReceivers=4
  createMultipleTransactedReceivers=true
  connected=true
  supportedProtocols=[ftp]
  serviceOverrides=<none>
}
,  name='endpoint.ftp.XXXX.com.21.EDI.UAT.XXXX.UAT.InBound', mep=ONE_WAY, properties={}, transactionConfig=Transaction{factory=null, action=INDIFFERENT, timeout=0}, deleteUnacceptedMessages=false, initialState=started, responseTimeout=10000, endpointEncoding=UTF-8, disableTransportTransformer=false}
********************************************************************************
Exception stack is:
1. Read timed out (java.net.SocketTimeoutException)
  java.net.SocketInputStream:-2 (null)
2. Failed to receive event over: DefaultInboundEndpoint{endpointUri=ftp://svelmurugan:<password>@XXX.com/EDI/UAT/XXX/InBound/, connector=EEFtpConnector
{
  name=connector.ftp.mule.default
  lifecycle=start
  this=4fd998e8
  numberOfConcurrentTransactedReceivers=4
  createMultipleTransactedReceivers=true
  connected=true
  supportedProtocols=[ftp]
  serviceOverrides=<none>
}
,  name='endpoint.ftp.XXXX.com.21.EDI.UAT.XXX.UAT.InBound', mep=ONE_WAY, properties={}, transactionConfig=Transaction{factory=null, action=INDIFFERENT, timeout=0}, deleteUnacceptedMessages=false, initialState=started, responseTimeout=10000, endpointEncoding=UTF-8, disableTransportTransformer=false} (timeout=1000) (org.mule.api.transport.ReceiveException)
  org.mule.transport.AbstractMessageRequester:128 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/transport/ReceiveException.html)
********************************************************************************
Root Exception stack trace:
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.readLine(BufferedReader.java:317)
	at java.io.BufferedReader.readLine(BufferedReader.java:382)
	at org.apache.commons.net.ftp.FTPFileEntryParserImpl.readNextEntry(FTPFileEntryParserImpl.java:53)
	at org.apache.commons.net.ftp.FTPListParseEngine.readStream(FTPListParseEngine.java:157)
	at org.apache.commons.net.ftp.FTPListParseEngine.readServerList(FTPListParseEngine.java:101)
	at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:2551)
	at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:2519)
	at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2275)
	at org.mule.transport.ftp.FtpConnector.isFile(FtpConnector.java:694)
	at org.mule.transport.ftp.FtpMessageRequester.findFileToProcess(FtpMessageRequester.java:154)
	at org.mule.transport.ftp.FtpMessageRequester.doRequest(FtpMessageRequester.java:93)
	at org.mule.transport.AbstractMessageRequester.request(AbstractMessageRequester.java:94)
	at org.mule.transport.AbstractConnector.request(AbstractConnector.java:2220)
	at org.mule.endpoint.DefaultInboundEndpoint.request(DefaultInboundEndpoint.java:80)
	at org.mule.client.DefaultLocalMuleClient.request(DefaultLocalMuleClient.java:183)
	at org.mule.module.MuleRequesterModule.request(MuleRequesterModule.java:60)
	at org.mule.module.processors.RequestMessageProcessor$1.process(RequestMessageProcessor.java:163)
	at org.mule.module.adapters.MuleRequesterModuleProcessAdapter$1.execute(MuleRequesterModuleProcessAdapter.java:36)
	at org.mule.module.processors.RequestMessageProcessor.doProcess(RequestMessageProcessor.java:149)
	at org.mule.devkit.processor.DevkitBasedMessageProcessor.process(DevkitBasedMessageProcessor.java:88)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:88)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:98)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)
	at org.mule.routing.outbound.AbstractMessageSequenceSplitter.processParts(AbstractMessageSequenceSplitter.java:129)
	at org.mule.routing.outbound.AbstractMessageSequenceSplitter.process(AbstractMessageSequenceSplitter.java:59)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:88)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.routing.Foreach.process(Foreach.java:94)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorEx...
********************************************************************************

Following line 80 of code from Mule-Requester project is not working.....

        else
        {
            muleEvent.getMessage().setPayload(NullPayload.getInstance());
        }

Please provide me quick reply on this issue. It's hanging my whole project here..

**Comment by devanad** [comment]
@sbeltramini any luck on this request ?

**Comment by sbeltramini** [comment]
I took a look into this and this is a problem within the FTP transport, not in the requester code.

In 3.7 the class org.mule.transport.ftp.FtpConnector has been modified to consider timeouts from the endpoints (this was not the case in previous versions, that's why I didn't fail before).

The change made in org.mule.transport.ftp.FtpConnector.createFtpClient(ImmutableEndpoint) is this:

`client.setDataTimeout(endpoint.getResponseTimeout());`

This reads the timeout from the *endpoint* not from the Requester's configuration, so even if you set a timeout of, say, 1 second, the FTP connector will ignore it and use the default 10 seconds.

You can modify that timeout by calling the resource this way:
`<mulerequester:request config-ref="Mule_Requester" resource="ftp://user:password@localhost:9999/s/tmp/ftptest/sample.txt?responseTimeout=5000" doc:name="Mule Requester"/>
`
Note the value for responseTimeout in the resource URL.

Again, the disparity between those 2 timeouts is an issue in the FTP transport itself, so it cannot be fixed in the Requester module.
