### ISSUE TITLE
How to close SFTP connection in module requestor

### ISSUE THREAD

**Issue by neerpathak** [mulesoft/mule-module-requester#23]
we have a requirement where we have to download multiple files from the SFTP locations. when we are using module requestor it seems it is making the connection and then not closing it and I am gettting error after download of 1 or 2 files.

Let me know how this can resolved.

**Comment by sbeltramini** [comment]
The connections are handled by the underlying transport (SFTP in this case) not by the Requester. The requester doesn't open nor close the connection by itself.

What error are you getting?

**Comment by neerpathak** [comment]
we need to download like 10 number of files from SFTP. after downloading 4 files it will start giving the error as authentication failed as we have defined 4 maximum connections. 

Root Exception stack trace:
java.io.IOException: Error during login to user@host: Auth fail
	at org.mule.transport.sftp.SftpClient.logAndThrowLoginError(SftpClient.java:214)
	at org.mule.transport.sftp.SftpClient.login(SftpClient.java:155)
	at org.mule.transport.sftp.SftpConnectionFactory.createClient(SftpConnectionFactory.java:108)
	at org.mule.transport.sftp.SftpConnector.createSftpClient(SftpConnector.java:190)
	at org.mule.transport.sftp.SftpConnector.createSftpClient(SftpConnector.java:173)
	at org.mule.transport.sftp.SftpReceiverRequesterUtil.getAvailableFiles(SftpReceiverRequesterUtil.java:72)
	at org.mule.transport.sftp.SftpMessageRequester.doRequest(SftpMessageRequester.java:39)
	at org.mule.transport.AbstractMessageRequester.request(AbstractMessageRequester.java:94)
	at org.mule.transport.AbstractConnector.request(AbstractConnector.java:2220)
	at org.mule.endpoint.DefaultInboundEndpoint.request(DefaultInboundEndpoint.java:80)
	at org.mule.client.DefaultLocalMuleClient.request(DefaultLocalMuleClient.java:183)
	at org.mule.module.MuleRequesterModule.request(MuleRequesterModule.java:60)
	at org.mule.module.processors.RequestMessageProcessor$1.process(RequestMessageProcessor.java:163)
	at org.mule.module.adapters.MuleRequesterModuleProcessAdapter$1.execute(MuleRequesterModuleProcessAdapter.java:36)
	at org.mule.module.processors.RequestMessageProcessor.doProcess(RequestMessageProcessor.java:149)
	at org.mule.devkit.processor.DevkitBasedMessageProcessor.process(DevkitBasedMessageProcessor.java:88)
	at org.mule.execution.ExceptionToMessagingExceptionExecu

**Comment by PabloCamino** [comment]
Hi @neerpathak the issue you are describing is a bug when using the requester for SFTP on Mule 3.7, upgrade your runtime version to Mule 3.8 and the issue should go away.
Best! 😎

**Comment by gouravsood** [comment]
Even on Mule 3.8, I have seen that happening. I think its still open issue.

**Comment by gouravsood** [comment]
Below is the exception:

`ERROR 2016-08-16 06:42:21,471 [[banking-sftp].InputSFTP.receiver.02] org.mule.transport.sftp.SftpClient: Error during login to user@host
com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512) ~[jsch-0.1.51.jar:?]
	at com.jcraft.jsch.Session.connect(Session.java:183) ~[jsch-0.1.51.jar:?]
	at org.mule.transport.sftp.SftpClient.login(SftpClient.java:147) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpConnectionFactory.createClient(SftpConnectionFactory.java:116) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpConnector.createSftpClient(SftpConnector.java:195) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpConnector.createSftpClient(SftpConnector.java:178) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpReceiverRequesterUtil.getAvailableFiles(SftpReceiverRequesterUtil.java:72) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpMessageReceiver.poll(SftpMessageReceiver.java:90) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.AbstractPollingMessageReceiver.performPoll(AbstractPollingMessageReceiver.java:216) ~[mule-core-3.8.0.jar:3.8.0]
	at org.mule.transport.PollingReceiverWorker.poll(PollingReceiverWorker.java:80) ~[mule-core-3.8.0.jar:3.8.0]
	at org.mule.transport.PollingReceiverWorker.run(PollingReceiverWorker.java:49) ~[mule-core-3.8.0.jar:3.8.0]
	at org.mule.transport.TrackingWorkManager$TrackeableWork.run(TrackingWorkManager.java:267) ~[mule-core-3.8.0.jar:3.8.0]
	at org.mule.work.WorkerContext.run(WorkerContext.java:286) ~[mule-core-3.8.0.jar:3.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
ERROR 2016-08-16 06:42:21,472 [[banking-sftp].InputSFTP.receiver.02] org.mule.transport.sftp.SftpMessageReceiver: Error in poll
org.mule.transport.ConnectException: Error during login to user@host: Auth fail (java.io.IOException)
	at org.mule.transport.sftp.SftpMessageReceiver.poll(SftpMessageReceiver.java:95) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.AbstractPollingMessageReceiver.performPoll(AbstractPollingMessageReceiver.java:216) ~[mule-core-3.8.0.jar:3.8.0]
	at org.mule.transport.PollingReceiverWorker.poll(PollingReceiverWorker.java:80) ~[mule-core-3.8.0.jar:3.8.0]
	at org.mule.transport.PollingReceiverWorker.run(PollingReceiverWorker.java:49) ~[mule-core-3.8.0.jar:3.8.0]
	at org.mule.transport.TrackingWorkManager$TrackeableWork.run(TrackingWorkManager.java:267) ~[mule-core-3.8.0.jar:3.8.0]
	at org.mule.work.WorkerContext.run(WorkerContext.java:286) ~[mule-core-3.8.0.jar:3.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.io.IOException: Error during login to user@host: Auth fail
	at org.mule.transport.sftp.SftpClient.logAndThrowLoginError(SftpClient.java:239) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpClient.login(SftpClient.java:157) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpConnectionFactory.createClient(SftpConnectionFactory.java:116) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpConnector.createSftpClient(SftpConnector.java:195) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpConnector.createSftpClient(SftpConnector.java:178) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpReceiverRequesterUtil.getAvailableFiles(SftpReceiverRequesterUtil.java:72) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	at org.mule.transport.sftp.SftpMessageReceiver.poll(SftpMessageReceiver.java:90) ~[mule-transport-sftp-3.8.0.jar:3.8.0]
	... 8 more
ERROR 2016-08-16 06:42:21,472 [[banking-sftp].InputSFTP.receiver.02] org.mule.exception.DefaultSystemExceptionStrategy: 
********************************************************************************
Message               : Error during login to user@host: Auth fail (java.io.IOException)
Element               : SftpMessageReceiver{this=6fd6cc3, receiverKey=sftp://host:22/path/test, endpoint=sftp://user:****@host:22/path/test} @ app
--------------------------------------------------------------------------------
Root Exception stack trace:
java.io.IOException: Error during login to user@host: Auth fail
	at org.mule.transport.sftp.SftpClient.logAndThrowLoginError(SftpClient.java:239)
	at org.mule.transport.sftp.SftpClient.login(SftpClient.java:157)
	at org.mule.transport.sftp.SftpConnectionFactory.createClient(SftpConnectionFactory.java:116)
	at org.mule.transport.sftp.SftpConnector.createSftpClient(SftpConnector.java:195)
	at org.mule.transport.sftp.SftpConnector.createSftpClient(SftpConnector.java:178)
	at org.mule.transport.sftp.SftpReceiverRequesterUtil.getAvailableFiles(SftpReceiverRequesterUtil.java:72)
	at org.mule.transport.sftp.SftpMessageReceiver.poll(SftpMessageReceiver.java:90)
	at org.mule.transport.AbstractPollingMessageReceiver.performPoll(AbstractPollingMessageReceiver.java:216)
	at org.mule.transport.PollingReceiverWorker.poll(PollingReceiverWorker.java:80)
	at org.mule.transport.PollingReceiverWorker.run(PollingReceiverWorker.java:49)
	at org.mule.transport.TrackingWorkManager$TrackeableWork.run(TrackingWorkManager.java:267)
	at org.mule.work.WorkerContext.run(WorkerContext.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

********************************************************************************

INFO  2016-08-16 06:42:21,472 [[banking-sftp].InputSFTP.receiver.02] org.mule.exception.DefaultSystemExceptionStrategy: Exception caught is a ConnectException, attempting to reconnect...
INFO  2016-08-16 06:42:21,472 [[banking-sftp].InputSFTP.receiver.02] org.mule.lifecycle.AbstractLifecycleManager: Stopping connector: InputSFTP
INFO  2016-08-16 06:42:21,489 [[banking-sftp].InputSFTP.receiver.02] org.mule.lifecycle.AbstractLifecycleManager: Stopping: 'null'. Object is: SftpMessageReceiver
INFO  2016-08-16 06:42:32,548 [[banking-sftp].InputSFTP.receiver.02] org.mule.lifecycle.AbstractLifecycleManager: Stopping: 'null'. Object is: SftpMessageReceiver
ERROR 2016-08-16 06:42:37,551 [[banking-sftp].InputSFTP.receiver.02] org.mule.exception.DefaultSystemExceptionStrategy: 
********************************************************************************
Message               : Error during login to user@host: Auth fail (java.io.IOException)
Element               : SftpMessageReceiver{this=6fd6cc3, receiverKey=sftp://host:22/path/test, endpoint=sftp://user:****@host:22/path/test} @ app
--------------------------------------------------------------------------------
Root Exception stack trace:
java.io.IOException: Error during login to user@host: Auth fail
	at org.mule.transport.sftp.SftpClient.logAndThrowLoginError(SftpClient.java:239)
	at org.mule.transport.sftp.SftpClient.login(SftpClient.java:157)
	at org.mule.transport.sftp.SftpConnectionFactory.createClient(SftpConnectionFactory.java:116)
	at org.mule.transport.sftp.SftpConnector.createSftpClient(SftpConnector.java:195)
	at org.mule.transport.sftp.SftpConnector.createSftpClient(SftpConnector.java:178)
	at org.mule.transport.sftp.SftpReceiverRequesterUtil.getAvailableFiles(SftpReceiverRequesterUtil.java:72)
	at org.mule.transport.sftp.SftpMessageReceiver.poll(SftpMessageReceiver.java:90)
	at org.mule.transport.AbstractPollingMessageReceiver.performPoll(AbstractPollingMessageReceiver.java:216)
	at org.mule.transport.PollingReceiverWorker.poll(PollingReceiverWorker.java:80)
	at org.mule.transport.PollingReceiverWorker.run(PollingReceiverWorker.java:49)
	at org.mule.transport.TrackingWorkManager$TrackeableWork.run(TrackingWorkManager.java:267)
	at org.mule.work.WorkerContext.run(WorkerContext.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

********************************************************************************

INFO  2016-08-16 06:42:37,551 [[banking-sftp].InputSFTP.receiver.02] org.mule.exception.DefaultSystemExceptionStrategy: Exception caught is a ConnectException, attempting to reconnect...
ERROR 2016-08-16 06:42:37,551 [[banking-sftp].InputSFTP.receiver.02] org.mule.exception.DefaultSystemExceptionStrategy: Already in lifecycle phase 'stop', cannot fire the same phase twice
INFO  2016-08-16 06:42:37,567 [[banking-sftp].Mule.02] org.mule.transport.sftp.SftpMessageReceiver: Connecting clusterizable message receiver`

**Comment by PabloCamino** [comment]
Hi @gouravsood , did you find a way around this issue?
If you are still having the same problem please add a link to a sample application that reproduces the issue, exported from Studio as a deployable ZIP archive, and I'll try yo have a look at it.

**Comment by emoran** [comment]
Any one found a solution? I also having this same problem.

**Comment by BaratMohan** [comment]
Anyone got a solution, i do have the same issue and this occurs intermittently

**Comment by PabloCamino** [comment]
@emoran @BaratMohan If still experience the issue, even using 3.9 runtime, please provide a sample application to inspect that exhibits this behavior. Best regards.

**Comment by kkk-f17** [comment]
Hi, I'm also facing the same issue and my mule runtime: 3.8.3. Any solution?

**Comment by kkk-f17** [comment]
> @emoran @BaratMohan If still experience the issue, even using 3.9 runtime, please provide a sample application to inspect that exhibits this behavior. Best regards.

I'm also facing the same issue and my mule runtime: 3.8.3. Any solution?

**Comment by PabloCamino** [comment]
Hi @kkk-f17 , please try using latest version, 3.9.3. You may also consider Mule 4 where the Requester Module is no longer needed as you have operation based connectors.
Regards.
