### ISSUE TITLE
mule requester xml schema is missing 

### ISSUE THREAD

**Issue by ashajjar** [mulesoft/mule-module-requester#39]
When I use mule requester in one of my flows .. it fails to load and shows this exception:

``` java
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'mulerequester:request'. One of '{"http://www.mulesoft.org/schema/mule/core":abstract-message-processor, "http://www.mulesoft.org/schema/mule/core":abstract-outbound-endpoint, "http://www.mulesoft.org/schema/mule/core":abstract-mixed-content-message-processor}' is expected.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[?:?]
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source) ~[?:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[?:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[?:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[?:?]
	at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source) ~[?:?]
	at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source) ~[?:?]
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source) ~[?:?]
	at org.apache.xerces.impl.xs.XMLSchemaValidator.emptyElement(Unknown Source) ~[?:?]
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[?:?]
	at ....
        .....
        ..... etc
```

When I try to open this URL (http://www.mulesoft.org/schema/mule/mulerequester/) which is supposed to be where the schema is for the requester, it gives 404. 

Am I missing something or is there a new schema url ? 

Thanks

**Comment by PabloCamino** [comment]
Hello @ashajjar , have you followed the installation steps before using the Requester?
https://github.com/mulesoft/mule-module-requester#installation
It seems you're missing a dependency.

**Comment by ashajjar** [comment]
Yes ... I followed the steps :) 

Did you try to open the link of the schema?! it points to non-existing location !

**Comment by PabloCamino** [comment]
Hello @ashajjar , it's common for Mule message processors to declare a namespace location as a URL that's actually non-resolvable. When you add the dependencies this URL is mapped to an XSD packed within the JAR file. This might be a little confusing but is a commonplace with Mule connectors.
Can you provide your project exported from Studio as a deployable ZIP to see what's going on?

**Comment by rbaizabal** [comment]
Hi @ashajjar, Could you solve the problem? I am currently in the same situation and I do not know what to do

**Comment by mdasu** [comment]
Same issue here.  Installed connector properly but error persists.

**Comment by serbanvasile66** [comment]
Can you please specify what you mean by pom update? What IDE are you using? Anypoint Studio?

**Comment by ashajjar** [comment]
I am not sure how did I solve that, or if I solved it at all ! I am sorry this was long time ago. But now from reading the exception, I am guessing it could be a good idea to try adding the namespace in the namespaces definitions top of the flow.xml file
