### ISSUE TITLE
Attribute 'config-ref' is not allowed to appear in element 'mulerequester:request'.

### ISSUE THREAD

**Issue by sonamsamdupkhangsar** [mulesoft/mule-module-requester#41]
I am using Mule ESB 3.9.1 runtime and using mule-module-requester version 1.5.  

I have the following mule requester config:

    `<mulerequester:config name="Mule_Requester" doc:name="Mule Requester"/>`

which is used in the following config:

`  <mulerequester:request config-ref="Mule_Requester" resource="<SOMETHING_HERE>" doc:name="Mule Requester" returnClass="java.lang.String" throwExceptionOnTimeout="true" timeout="10000"/>
`

When I deploy my mule app I get the following error:

> org.mule.module.launcher.application.DefaultMuleApplication: null
org.xml.sax.SAXParseException: cvc-complex-type.3.2.2: Attribute 'config-ref' is not allowed to appear in element 'mulerequester:request'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processAttributes(XMLSchemaValidator.java:2707) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2050) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:760) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_152]
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.mule.config.spring.MuleDocumentLoa

**Comment by sonamsamdupkhangsar** [comment]
Let me take it out and deploy again.  Thanks

**Comment by sonamsamdupkhangsar** [comment]
Hi @PabloCamino 
So I removed the config-ref (config-ref="Mule_Requester") and have the following
`<mulerequester:request  resource="<SOMETHING_HERE>" doc:name="Mule Requester" returnClass="java.lang.String" throwExceptionOnTimeout="true" timeout="10000"/>`

and still have on Line 109 referenced in the stacktrace:
` <mulerequester:config name="Mule_Requester" doc:name="Mule Requester"/>`

I am getting exception and failing to deploy still.  The following is the stack trace:

`caused by: org.mule.api.config.ConfigurationException: Line 109 in XML document from URL [file:/opt/mule-enterprise-standalone-3.9.1/apps/myapp/global_configurations.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 109; columnNumber: 76; cvc-complex-type.2.4.a: Invalid content was found starting with element 'mulerequester:config'. One of '{`


Is the following config not correct?
`<mulerequester:config name="Mule_Requester" doc:name="Mule Requester"/>`

**Comment by RishulSaxena** [comment]
Hi I am facing a similar issue. 
![image](https://user-images.githubusercontent.com/63290609/86905023-236a1580-c12f-11ea-9305-d2a92e3e677e.png)     
Were you able to resolve this issue. Please give suggestions. Than in advance.

**Comment by PabloCamino** [comment]
Hello @RishulSaxena , this error does not seem related to the Mule Requester Module. I will be closing this issue. If you require assistance please head to https://help.mulesoft.com/s/
Best!

**Comment by chravigithub** [comment]
> Hi I am facing a similar issue.
> ![image](https://user-images.githubusercontent.com/63290609/86905023-236a1580-c12f-11ea-9305-d2a92e3e677e.png)
> Were you able to resolve this issue. Please give suggestions. Than in advance.

Hi RishulSaxena, I am facing a similar issue. Were you able to fix this. Kindly help me if you have the resolution.

**Comment by RishulSaxena** [comment]
Please check that the port numbers are unique and not repeated. That's the only thing I can think of.
